[package]
name = "librna-sys"
authors = ["Vincent Messow <contact@vncnt.eu>"]
build = "src/build.rs"
links = "RNA"
repository = "https://github.com/fncnt/librna-sys"
readme = "README.md"
license = "MIT"
description = "Low-level bindings for libRNA of viennaRNA with support for linux."
include = ["src/*", "Cargo.toml", "README.md", "COPYING"]
keywords = ["viennarna", "rna", "bioinformatics", "sys"]
categories = ["api-bindings", "external-ffi-bindings", "science"]
version = "0.1.0"
edition = "2018"

[lib]
doctest = false
crate-type = ["lib"]

[build-dependencies]
bindgen = "~0.58"
pkg-config = { optional = true, version = "~0.3" }

[dependencies]

[dev-dependencies]
libc = "~0.2"
pyo3 = { version = "~0.13", features = ["extension-module"] }

[features]
default = []
auto = ["pkg-config"]


[[example]]
name = "bpdist"
doctest = false
crate-type = ["lib", "cdylib"]

#default = ["pyo3/extension-module"]

